#!/usr/bin/env bash
# vim: set ft=sh

if [[ $(uname) != 'Darwin' ]]; then
    echo "OSX only"
    exit 1
fi

INSTALLED=0

command -v brew && INSTALLED=1

if [[ $INSTALLED -eq 0 ]]; then
    echo "# Brew isn't installed! Get it here:"
    echo "open http://brew.sh/"
    exit 1
fi

APPS="git \
    zsh \
    curl \
    htop-osx \
    httpie \
    jq \
    nmap \
    node \
    pv \
    python \
    python3 \
    ssh-copy-id \
    the_silver_searcher \
    tig \
    vimpager \
    wget \
    shellcheck \
    mpv \
    vim \
    vimpager"

brew update
brew upgrade

brew install $APPS

brew cleanup
