#!/usr/bin/env bash
# vim: set ft=sh

if [[ $(uname) != 'Darwin' ]]; then
    echo "OSX only"
    exit 1
fi

APPS="iterm2-beta \
    firefoxdeveloperedition \
    dropbox \
    google-drive \
    keepassx \
    itsycal \
    alfred \
    flux \
    sublime-text-dev \
    steam \
    skype \
    spotify \
    chromium \
    karabiner \
    smoothmouse"

brew tap caskroom/cask
brew tap caskroom/versions

brew cask install $APPS
