#!/usr/bin/env bash
# vim: set ft=sh

if [[ $(uname) != 'Darwin' ]]; then
    echo "OSX only"
    exit 1
fi

APPS="iterm2-beta \
    firefox-beta \
    dropbox \
    google-backup-and-sync \
    keepassx \
    itsycal \
    alfred \
    flux \
    sublime-text-dev \
    steam \
    spotify"

brew tap caskroom/cask
brew tap caskroom/versions

brew cask install $APPS
