#!/usr/bin/env zsh

DOTFILES=$(dirname "$0:A")

setopt EXTENDED_GLOB

for i in $DOTFILES/^install(.N); do
	ln -v -s "$i" "$HOME/$(basename "$i")"
done

for i in $DOTFILES/.*; do
	ln -v -s "$i" "$HOME/$(basename "$i")"
done
