#!/usr/bin/env zsh
set -euo pipefail
set -x

DOTFILES=$(dirname $0:A)

export ZIM_HOME="$HOME/.zim"
ZSHENV="$HOME/.zshenv"
ZLOGIN="$HOME/.zlogin"

# Install zim
mkdir -p "$ZIM_HOME"
curl -L https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh -o "$ZIM_HOME/zimfw.zsh"

if ! grep -q ZIM "$ZSHENV"; then
    echo ': ${ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim}' >> "$ZSHENV"
fi

if ! grep -q ZIM "$ZLOGIN"; then
    echo 'source ${ZIM_HOME}/login_init.zsh -q &!' >> "$ZLOGIN"
fi

# Personal configuration
ln -sf "$DOTFILES/.zshrc" "$HOME/.zshrc"
ln -sf "$DOTFILES/.zimrc" "$HOME/.zimrc"

# Copy over prompt theme
mkdir -p "$HOME/.zfunctions"
ln -sf "$DOTFILES/amini-theme.zsh" "$HOME/.zfunctions/prompt_amini_setup"

local ZSH_PATH="$(which zsh)"
if [ "$(uname)" = 'Darwin' ]; then
    ZSH_PATH="$(brew --prefix)/bin/zsh"
fi

if ! grep -q "$ZSH_PATH" /etc/shells; then
    # https://stackoverflow.com/a/44549662
    sudo sh -c "echo $ZSH_PATH >> /etc/shells"
fi

chsh -s "$ZSH_PATH"

$ZSH_PATH -ic "source $ZIM_HOME/zimfw.zsh install"
