#!/usr/bin/env zsh
set -euo pipefail
set -x

DOTFILES=$(dirname $0:A)

# Install zim
git clone --recursive https://github.com/zimfw/zimfw.git ${ZDOTDIR:-${HOME}}/.zim

# Prepend the initialization templates to your configs:
for template_file in ${ZDOTDIR:-${HOME}}/.zim/templates/*; do
    user_file="${ZDOTDIR:-${HOME}}/.${template_file:t}"
    cat ${template_file} ${user_file}(.N) > ${user_file}.tmp && mv ${user_file}{.tmp,}
done

# Personal configuration
ln -sf "$DOTFILES/.zshrc" "$HOME/.zshrc"
ln -sf "$DOTFILES/.zimrc" "$HOME/.zimrc"

# Copy over prompt theme
mkdir -p "$HOME/.zprompts"
ln -sf "$DOTFILES/amini-theme.zsh" "$HOME/.zprompts/prompt_amini_setup"

local ZSH_PATH="$(brew --prefix)/bin/zsh"

if ! grep -q "$ZSH_PATH" /etc/shells; then
    # https://stackoverflow.com/a/44549662
    sudo sh -c "echo $ZSH_PATH >> /etc/shells"
fi

chsh -s "$ZSH_PATH"

set +x
echo "Run this on next shell start to finish optimization
(this is only needed once, hereafter it will happen upon desktop/tty login):

    source ${ZDOTDIR:-${HOME}}/.zlogin"
